database:
  ==: vg.civcraft.mc.civmodcore.dao.DatabaseCredentials
  plugin: Arsenal
  user: 'mc_arsenal'
  password: 'minecraft'
  host: localhost
  port: 3306
  database: arsenal
  poolsize: 5
  connection_timeout: 10000
  idle_timeout: 600000
  max_lifetime: 7200000
artillery:
  types:
    field-artillery:
      id: 1
      display-name: Field Artillery
      blueprint-name: field-artillery.json
      clazz-name: dev.jayms.arsenal.artillery.FieldArtillery