name: Arsenal
main: dev.jayms.arsenal.Arsenal
version: 1.0
authors:
  - jayms
depend:
  - NameLayer
  - CivModCore
  - Citadel
  - Bastion
softdepend:
  - HolographicDisplays
description: An Arsenal is a collection of weapons and military equipment.
api-version: 1.17
permissions:
  arsenal.admin:
    default: op